name       : czkawka
version    : 6.1.0
release    : 6
source     :
    - https://github.com/qarmin/czkawka/archive/refs/tags/6.1.0.tar.gz : 63e64c717a93b3d5210d6a4718833fdbf3ad7b28c9b74a243d9de3ab1ee6ad5a
homepage   : https://qarmin.github.io/czkawka/
license    :
    - CC-BY-4.0
    - MIT
component  : system.utils
summary    : Multi functional app to find duplicates, empty folders, similar images etc
description: |
    Czkawka is a simple, fast and free app to remove unnecessary files from your computer.
    It's an alternative for fslint.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --workspace
install    : |
    %cargo_install czkawka_cli czkawka_gui

    install -Dm00644 data/com.github.qarmin.czkawka.desktop -t $installdir/usr/share/applications
    install -Dm00644 data/icons/*.svg -t $installdir/usr/share/icons/hicolor/scalable/apps
    install -Dm00644 data/com.github.qarmin.czkawka.metainfo.xml -t $installdir/usr/share/metainfo
