name       : flacon
version    : 11.2.0
release    : 14
source     :
    - https://github.com/flacon/flacon/archive/refs/tags/v11.2.0.tar.gz : 5009025a1f3b3f5829631578d9a4985efded85cdf754f1c1594cf3d41f3890a7
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Extracts audio tracks from an audio CD image to separate tracks
description: |
    Flacon extracts individual tracks from one big audio file containing the entire album of music and saves them as separate audio files.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(taglib)
    - pkgconfig(uchardet)
    - libflac
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - sox
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
rundeps    :
    - lame
    - libflac
    - mp3gain
    - opus-tools
    - sox
    - vorbis-tools
    - vorbisgain
    - wavpack-utils
setup      : |
    rm -rf tests/data/testConvert/{'17.2 issue 176 ALAC','18.2 tags ALAC','18.3 tags AAC'}
    rm -rf tests/data/testReplayGain/{'01.2 track ALAC','01.3 track AAC','02.2 album ALAC','02.3 album AAC'}
    %patch -p1 < $pkgfiles/0001-Don-t-test-Monkey-s-Audio-and-tta.patch
    %cmake_ninja -DBUILD_TESTS=Yes
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/share/applications/{flacon.desktop,com.github.Flacon.desktop}
check      : |
    export CTEST_OUTPUT_ON_FAILURE=1
    %ninja_check
