name       : freeimage
version    : 3.18.0
release    : 12
source     :
    - https://netcologne.dl.sourceforge.net/project/freeimage/Source%20Distribution/3.18.0/FreeImage3180.zip : f41379682f9ada94ea7b34fe86bf9ee00935a3147be41b6569c9605a53e438fd
homepage   : https://freeimage.sourceforge.io/
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Library to support graphics image formats.
description: |
    FreeImage is a library project for developers who would like to support popular graphics image formats (PNG, JPEG, TIFF, BMP and others).
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw_r)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - dos2unix
    - doxygen
    - jxrlib-devel
    - tree
libsplit   : no
fatfakeroot: no
setup      : |
    %apply_patches

    # remove all included libs to make sure these don't get used during compile
    rm -r Source/Lib* Source/ZLib Source/OpenEXR

    # clear files which cannot be built due to dependencies on private headers
    # (see also unbundle patch)
    true > Source/FreeImage/PluginG3.cpp
    true > Source/FreeImageToolkit/JPEGTransform.cpp

    # sanitize encodings / line endings
    for file in `find . -type f -name '*.c' -or -name '*.cpp' -or -name '*.h' -or -name '*.txt' -or -name Makefile`; do
        iconv --from=ISO-8859-15 --to=UTF-8 $file > $file.new && \
        sed -i 's|\r||g' $file.new && \
        touch -r $file $file.new && mv $file.new $file
    done
build      : |
    sh gensrclist.sh
    sh genfipsrclist.sh
    %make -f Makefile.gnu
    %make -f Makefile.fip
    pushd Wrapper/FreeImagePlus/doc
    doxygen FreeImagePlus.dox
    popd
install    : |
    install -Dm0755 Dist/libfreeimage-$version.so $installdir/%libdir%/libfreeimage-$version.so
    ln -srv $installdir/%libdir%/libfreeimage-$version.so $installdir/%libdir%/libfreeimage.so.3
    ln -srv $installdir/%libdir%/libfreeimage.so.3 $installdir/%libdir%/libfreeimage.so
    install -Dm0755 Dist/libfreeimageplus-$version.so $installdir/%libdir%/libfreeimageplus-$version.so
    ln -srv $installdir/%libdir%/libfreeimageplus-$version.so $installdir/%libdir%/libfreeimageplus.so.3
    ln -srv $installdir/%libdir%/libfreeimageplus.so.3 $installdir/%libdir%/libfreeimageplus.so
    install -Dm0644 Source/FreeImage.h $installdir/usr/include/FreeImage.h
    install -Dm0644 Wrapper/FreeImagePlus/FreeImagePlus.h $installdir/usr/include/FreeImagePlus.h
    tree $installdir
