name       : mupen64plus
version    : 2.6.0
release    : 24
source     :
    - git|https://github.com/mupen64plus/mupen64plus-core.git : 5ec999ef07905a3bad6319902479150ab4c3f060
    - git|https://github.com/mupen64plus/mupen64plus-audio-sdl.git : 07c866bd2b897fcbce2131dc36066c179422c3c9
    - git|https://github.com/mupen64plus/mupen64plus-input-sdl.git : 8889a0f3ecff726959389d988da810a2829c61b5
    - git|https://github.com/mupen64plus/mupen64plus-rsp-cxd4.git : 01c6cd826ebd0eb975b4aca3297170fe6858e49d
    - git|https://github.com/mupen64plus/mupen64plus-rsp-hle.git : 2d3808549521c09e252d5a0f9d8d747fc4e6ae99
    - git|https://github.com/mupen64plus/mupen64plus-rsp-z64.git : 0f32fbb27a817d0304453a238d938cdc43a0669f
    - git|https://github.com/mupen64plus/mupen64plus-video-arachnoid.git : 5e9ea510648b6e0f233796ae4ecaf99dd88175c0
    - git|https://github.com/mupen64plus/mupen64plus-video-glide64mk2.git : d82d5715111bc50cf6dd8066e531e9cc6fbb9eab
    - git|https://github.com/mupen64plus/mupen64plus-video-rice.git : fcf00779f08a9503ef30d26422f6b0350684820d
    - git|https://github.com/mupen64plus/mupen64plus-video-z64.git : 11f354a65a5b123fa8d18e761d52c2d3280a9333
    - git|https://github.com/mupen64plus/mupen64plus-ui-console.git : 44bc0d8e82da88efa2bd700472c10f9166314e00
license    :
    - GPL-2.0-only
    - CC0-1.0 #mupen64plus-rsp-cxd4
homepage   : http://mupen64plus.org/
component  : games.emulator
summary    : N64 emulator
description: |
    Mupen64Plus is a cross-platform plugin-based N64 emulator which is capable of accurately playing many games. Included are MIPS R4300 CPU emulators, with dynamic recompilers, and necessary plugins for audio, graphical rendering (RDP), signal co-processor (RSP), and input.
optimize   : lto
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(samplerate)
    - pkgconfig(sdl2)
    - pkgconfig(speex)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
environment: |
    export PLUGINS="audio-sdl input-sdl rsp-cxd4 rsp-hle rsp-z64 video-arachnoid video-glide64mk2 video-rice video-z64 ui-console"
setup      : |
    for plugin in $PLUGINS
    do
        cp -r $sources/mupen64plus-$plugin.git $workdir/$plugin
    done
build      : |
    for plugin in . $PLUGINS
    do
        %make -C $plugin/projects/unix all APIDIR=$workdir/src/api
    done
install    : |
    for plugin in . $PLUGINS
    do
       %make_install -C $plugin/projects/unix APIDIR=$workdir/src/api DESTDIR=$installdir PREFIX=/usr LIBDIR=%libdir% LDCONFIG="true"
    done
