name       : ripgrep-all
version    : 0.10.6
release    : 2
source     :
    - https://github.com/phiresky/ripgrep-all/archive/refs/tags/v0.10.6.tar.gz : 06cd619ad6638be206266a77fdf11034dc2dc15d97b3a057b0d6280a17334680
homepage   : https://github.com/phiresky/ripgrep-all
license    : AGPL-3.0-or-later
component  : system.utils
summary    : ripgrep-all (rga) allows you to search PDFs, e-books, Office documents, archive formats and more
description: |
    rga is a line-oriented search tool that allows you to look for a regex in a multitude of file types. rga wraps the awesome ripgrep and enables it to search in pdf, docx, sqlite, jpg, movie subtitles (mkv, mp4), etc.
networking : yes
builddeps  :
    - rust
rundeps    :
    - ripgrep
checkdeps  :
    - pandoc
    - poppler-utils
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install rga rga-preproc
check      : |
    %cargo_test
